dataset:
  name: Cabbage6
  train_dataset_dir: './data/Cabbage6/train'
  test_dataset_dir: './data/Cabbage6/test'
  image_size: 256
  n_channels: 3
  n_classes: 6
augmentation:
  use_random_crop: True
  use_random_horizontal_flip: True
  use_cutout: False
  use_random_erasing: False
  use_dual_cutout: False
  use_mixup: False
  use_ricap: False
  use_cutmix: False
  use_label_smoothing: False
